INSERT INTO category (nombre) VALUES ('Electrónica');
INSERT INTO category (nombre) VALUES ('Ropa');
INSERT INTO category (nombre) VALUES ('Libros');
INSERT INTO category (nombre) VALUES ('Hogar');
INSERT INTO category (nombre) VALUES ('Juguetes');
INSERT INTO category (nombre) VALUES ('Deportes');
INSERT INTO category (nombre) VALUES ('Alimentos');
INSERT INTO category (nombre) VALUES ('Belleza');
INSERT INTO category (nombre) VALUES ('Automotriz');
INSERT INTO category (nombre) VALUES ('Jardinería');
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Laptop', 15, 1);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Camiseta', 50, 2);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Novela', 30, 3);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Sofá', 5, 4);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Muñeca', 20, 5);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Balón de fútbol', 25, 6);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Cereal', 40, 7);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Shampoo', 35, 8);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Aceite de motor', 10, 9);
INSERT INTO product (nombre, cantidad, category_id) VALUES ('Maceta', 12, 10);